name: Testing workflow

on:
  push:
    branches:
      - feature/staff-user-interface
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: echo "Hello world"
        shell: bash
